services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    network_mode: host
    depends_on:
      - prometheus
      - node-exporter

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./provisioning/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter:latest
    privileged: true
    network_mode: host
