{
 "title": "Docker",
 "description": "Docker containers per instance",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_last_seen,job)"
    }
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(up,instance)" } },
   {
    "name": "name",
    "label": "Container",
    "query": {
     "query": "label_values(container_last_seen{job=\"$job\", instance=~\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "taminomara-hostoverview-panel",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "time() - container_last_seen{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance, name) (irate(container_cpu_usage_seconds_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - container_start_time_seconds{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "stat",
   "description": "Total CPU consumed by all containers, normalized by number of cores.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval])) / scalar(sum(machine_cpu_cores{job=\"$job\", instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "stat",
   "description": "Total memory working set consumed by all containers.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU usage by container, 1 core = 100%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (irate(container_cpu_usage_seconds_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage by container, user, 1 core = 100%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (irate(container_cpu_user_seconds_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage by container, system, 1 core = 100%",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (irate(container_cpu_system_seconds_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Working set by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (container_memory_working_set_bytes{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Total memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (container_memory_usage_bytes{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "RSS by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance, name) (container_memory_rss{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Cache memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (container_memory_cache{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Swap memory usage by container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (container_memory_swap{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"})",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "OOM Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(instance, name) (irate(container_oom_events_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{name}} @ {{instance}}"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Disk Read/Write Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(name, instance) (rate(container_fs_reads_bytes_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "Read: {{name}} @ {{instance}}"
    },
    {
     "expr": "sum by(name, instance) (rate(container_fs_writes_bytes_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "Write: {{name}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write IOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by(name, instance) (rate(container_fs_reads_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "Read: {{name}} @ {{instance}}"
    },
    {
     "expr": "sum by(name, instance) (rate(container_fs_writes_total{job=\"$job\", instance=~\"$instance\", name=~\"$name\", name!=\"\"}[$__rate_interval]))",
     "legendFormat": "Write: {{name}} @ {{instance}}"
    }
   ]
  }
 ]
}